"use client";

import { motion, useInView, AnimatePresence } from "framer-motion";
import { useRef, useState } from "react";
import { Check, Globe, Share2, Users } from "lucide-react";

const days = [
  { day: "Day 1", title: "Fly Kathmandu → Lukla, trek to Phakding", emoji: "✈️", hrs: "3–4 hrs" },
  { day: "Day 2", title: "Phakding to Namche Bazaar", emoji: "🏔️", hrs: "5–6 hrs" },
  { day: "Day 3", title: "Acclimatization in Namche", emoji: "🧘", hrs: "Rest day" },
  { day: "Day 4", title: "Namche to Tengboche Monastery", emoji: "🕌", hrs: "5–6 hrs" },
  { day: "Day 5", title: "Tengboche to Dingboche", emoji: "⛺", hrs: "5 hrs" },
];

const included = [
  ["✈️", "Kathmandu flights & transfers"],
  ["🏕️", "Teahouse accommodation all nights"],
  ["👨‍🦯", "Certified Sherpa guide + porter"],
  ["📋", "All permits auto-handled by NOMA"],
];

export function ItineraryPublish() {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-80px" });
  const [published, setPublished] = useState(false);
  const [publishing, setPublishing] = useState(false);

  function handlePublish() {
    if (published) return;
    setPublishing(true);
    setTimeout(() => { setPublishing(false); setPublished(true); }, 1400);
  }

  return (
    <section ref={ref} className="mx-auto max-w-5xl px-5 py-20">
      <div className="mb-10 text-center">
        <p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-600">Creator tools</p>
        <h2 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950 md:text-4xl">
          Build your trip page,{" "}
          <span className="bg-gradient-to-r from-emerald-600 to-teal-500 bg-clip-text text-transparent">
            share with followers
          </span>
        </h2>
        <p className="mx-auto mt-3 max-w-md text-base text-slate-500">
          NOMA generates a full itinerary from your brief. One click publishes a bookable page your audience can buy directly.
        </p>
      </div>

      <div className="grid gap-5 md:grid-cols-2">
        {/* Left — itinerary builder */}
        <div className="flex flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl shadow-slate-200/50">
          <div className="border-b border-slate-100 bg-slate-50 px-4 py-3">
            <p className="text-sm font-semibold text-slate-900">Trip Builder</p>
            <p className="text-xs text-slate-400">Everest Base Camp · 12 days · AI-generated</p>
          </div>

          <div className="flex-1 divide-y divide-slate-50 overflow-hidden p-2">
            {days.map((d, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 12 }}
                animate={inView ? { opacity: 1, y: 0 } : {}}
                transition={{ delay: i * 0.1 + 0.15, duration: 0.4 }}
                className="flex items-center gap-3 rounded-xl px-3 py-2.5 transition hover:bg-slate-50"
              >
                <span className="text-lg">{d.emoji}</span>
                <div className="flex-1 min-w-0">
                  <span className="text-[11px] font-semibold text-blue-600">{d.day}</span>
                  <p className="truncate text-sm font-medium text-slate-800">{d.title}</p>
                </div>
                <span className="shrink-0 text-xs text-slate-400">{d.hrs}</span>
              </motion.div>
            ))}

            <motion.p
              initial={{ opacity: 0 }}
              animate={inView ? { opacity: 1 } : {}}
              transition={{ delay: 0.75 }}
              className="px-3 py-2 text-center text-xs text-slate-400"
            >
              + 7 more days generated by AI
            </motion.p>
          </div>

          {/* Publish button */}
          <div className="border-t border-slate-100 p-3">
            <motion.button
              onClick={handlePublish}
              whileHover={!published ? { scale: 1.02 } : {}}
              whileTap={!published ? { scale: 0.97 } : {}}
              animate={published ? { backgroundColor: "#059669" } : {}}
              className="glass-button relative w-full overflow-hidden rounded-xl py-2.5 text-sm font-semibold text-white"
            >
              <AnimatePresence mode="wait">
                {publishing ? (
                  <motion.span
                    key="loading"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="flex items-center justify-center gap-2"
                  >
                    <motion.span
                      animate={{ rotate: 360 }}
                      transition={{ repeat: Infinity, duration: 0.8, ease: "linear" }}
                      className="inline-block"
                    >
                      ⏳
                    </motion.span>
                    Publishing…
                  </motion.span>
                ) : published ? (
                  <motion.span
                    key="done"
                    initial={{ opacity: 0, y: 6 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="flex items-center justify-center gap-2"
                  >
                    <Check size={15} />
                    Published — live now!
                  </motion.span>
                ) : (
                  <motion.span key="idle" className="flex items-center justify-center gap-2">
                    <Globe size={15} />
                    Publish Trip Page
                  </motion.span>
                )}
              </AnimatePresence>
            </motion.button>
          </div>
        </div>

        {/* Right — published page preview */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ delay: 0.35, duration: 0.5 }}
          className="flex flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl shadow-slate-200/50"
        >
          {/* Hero gradient */}
          <div className="relative h-32 bg-gradient-to-br from-blue-500 via-indigo-500 to-violet-600">
            <div className="absolute inset-0 flex flex-col items-center justify-center text-white">
              <p className="text-xs font-medium opacity-75">@sarahexplores presents</p>
              <p className="mt-1 text-xl font-bold tracking-tight">Everest Base Camp</p>
              <div className="mt-1 flex items-center gap-3 text-xs opacity-80">
                <span>Oct 15–27</span>
                <span>·</span>
                <span className="flex items-center gap-1"><Users size={11} /> 8 spots</span>
              </div>
            </div>

            {/* Live badge */}
            <AnimatePresence>
              {published && (
                <motion.div
                  initial={{ scale: 0, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  transition={{ type: "spring", stiffness: 400, damping: 20 }}
                  className="absolute right-3 top-3 flex items-center gap-1 rounded-full bg-emerald-500 px-2.5 py-1 text-[11px] font-bold text-white shadow-lg"
                >
                  <span className="relative flex h-1.5 w-1.5">
                    <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-white opacity-75" />
                    <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-white" />
                  </span>
                  LIVE
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          <div className="flex flex-1 flex-col p-4">
            {/* URL bar */}
            <div className="mb-4 flex items-center gap-1.5 rounded-lg bg-slate-50 px-3 py-2 text-xs">
              <span className="text-slate-400">noma.travel/trip/</span>
              <span className="font-semibold text-slate-700">ebc-oct-sarah</span>
              <motion.button
                whileHover={{ scale: 1.1 }}
                className="ml-auto text-slate-400 hover:text-slate-600"
              >
                <Share2 size={12} />
              </motion.button>
            </div>

            {/* Inclusions */}
            <div className="flex-1 space-y-2">
              {included.map(([emoji, text], i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, x: 10 }}
                  animate={inView ? { opacity: 1, x: 0 } : {}}
                  transition={{ delay: 0.5 + i * 0.09 }}
                  className="flex items-center gap-2.5 rounded-lg bg-slate-50 px-3 py-2 text-sm text-slate-700"
                >
                  <span>{emoji}</span>
                  <span>{text}</span>
                </motion.div>
              ))}
            </div>

            {/* CTA */}
            <motion.div
              initial={{ opacity: 0, y: 8 }}
              animate={inView ? { opacity: 1, y: 0 } : {}}
              transition={{ delay: 0.9 }}
              className="mt-4 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 py-3 text-center text-sm font-semibold text-white shadow-md shadow-blue-500/30"
            >
              Book my spot — $2,400
            </motion.div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
